# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image with version 16+ as the base image
FROM node:16-alpine AS build

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install pnpm (since it's used in the project)
RUN npm install -g pnpm

# Install dependencies and build the project
RUN pnpm install && pnpm run build

# Copy the rest of the application
COPY . .

# Expose the configuration directory
VOLUME ["/root/.hny"]

# Command to run the MCP server
ENTRYPOINT ["node", "build/index.mjs"]
