# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install pnpm
RUN npm install -g pnpm

# Create app directory
WORKDIR /app

# Copy package.json and lockfile
COPY package.json pnpm-lock.yaml ./

# Install dependencies (ignore scripts to avoid any unwanted pre/post install scripts)
RUN pnpm install --ignore-scripts

# Copy the rest of the source and config files
COPY . .

# Ensure a default config exists for deployment; if the user provides an override via MCP_HONEYCOMB_CONFIG, that file will be used
RUN if [ ! -f .mcp-honeycomb.json ]; then echo '{"environments": [{"name": "development", "apiKey": "dummy_api_key"}]}' > .mcp-honeycomb.json; fi

# Build the project
RUN pnpm run build

# Expose any necessary ports (if applicable)
# EXPOSE 3000

# Command to run the MCP server
CMD ["node", "build/index.mjs"]
