name: Run Evaluations

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  evaluate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build project
        run: pnpm run build
        
      - name: Create MCP config
        run: |
          echo '${{ secrets.MCP_CONFIG }}' > .mcp-honeycomb.json
          echo "Created MCP config file"
          
      - name: Run evaluations
        run: pnpm run eval
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          # Use only limited models for CI to save costs
          EVAL_MODELS: '{"openai":"gpt-4o","anthropic":"claude-3-5-haiku-latest"}'
          EVAL_CONCURRENCY: 2
          MCP_SERVER_COMMAND: "node build/index.mjs"
          
      - name: Find latest report
        id: find-report
        run: |
          LATEST_REPORT=$(ls -t eval/reports/*.html | head -1)
          echo "latest_report=$LATEST_REPORT" >> $GITHUB_OUTPUT
          
      - name: Post report summary to PR step
        if: github.event_name == 'pull_request'
        run: |
          echo "## Evaluation Results" > $GITHUB_STEP_SUMMARY
          echo "Ran evaluations with OpenAI and Anthropic models." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Summary" >> $GITHUB_STEP_SUMMARY
          echo "Latest report: $(basename ${{ steps.find-report.outputs.latest_report }})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The full report is available as a workflow artifact." >> $GITHUB_STEP_SUMMARY
      
      # Always upload reports as artifacts (using v4)
      - name: Upload reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-reports
          path: eval/reports/
          retention-days: 30
          
  # Separate job for GitHub Pages deployment (only runs on main branch)
  deploy:
    needs: evaluate
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: evaluation-reports
          path: reports
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4