name: Run Evaluations

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  evaluate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    # Only deploy to GitHub Pages from the main branch
    # For other branches, we'll just generate reports without deployment
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build project
        run: pnpm run build
        
      - name: Run evaluations
        run: pnpm run eval
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          # Use only limited models for CI to save costs
          EVAL_MODELS: '{"openai":"gpt-4o","anthropic":"claude-3-5-haiku-latest"}'
          EVAL_CONCURRENCY: 2
          
      - name: Find latest report
        id: find-report
        run: |
          LATEST_REPORT=$(ls -t eval/reports/*.html | head -1)
          echo "latest_report=$LATEST_REPORT" >> $GITHUB_OUTPUT
          
      - name: Post report summary to PR step
        if: github.event_name == 'pull_request'
        run: |
          cat eval/results/all-results-*.json
          
          echo "## Evaluation Results" > $GITHUB_STEP_SUMMARY
          echo "Ran evaluations with OpenAI and Anthropic models." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Summary" >> $GITHUB_STEP_SUMMARY
          echo "Latest report: $(basename ${{ steps.find-report.outputs.latest_report }})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The full report is available as a workflow artifact." >> $GITHUB_STEP_SUMMARY
      
      # Upload artifact for access after workflow completion
      - name: Upload reports artifact
        uses: actions/upload-artifact@v3
        with:
          name: evaluation-reports
          path: eval/reports/
          retention-days: 30
      
      # Conditional deployment to GitHub Pages (only from main branch)
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: eval/reports
          target-folder: reports