name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    # Run on all pull requests, regardless of target branch
    
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    # Setup PNPM - must be before setting up Node.js cache
    - name: Setup PNPM
      uses: pnpm/action-setup@v2
    
    # Setup Node.js cache after PNPM is installed
    - name: Setup Node.js with cache
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Run TypeScript type-checking
      run: pnpm exec tsc --noEmit
    
    - name: Run tests
      run: pnpm test
    
    - name: Run test with coverage
      run: pnpm test:coverage
      
    - name: Build
      run: pnpm build
      
    # Run evaluations only on PRs after tests pass
    - name: Run evaluations for pull requests
      if: github.event_name == 'pull_request' && success()
      run: |
        # Set up environment for evals
        echo '${{ secrets.MCP_CONFIG }}' > .mcp-honeycomb.json
        
        # Run the evaluations
        pnpm run eval
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        # Use only limited models for CI to save costs
        EVAL_MODELS: '{"openai":"gpt-4o","anthropic":"claude-3-5-haiku-latest"}'
        EVAL_CONCURRENCY: 2
        MCP_SERVER_COMMAND: "node build/index.mjs"
        
    # Upload evaluation reports as artifacts for PRs
    - name: Upload evaluation reports for pull requests
      if: github.event_name == 'pull_request' && success()
      uses: actions/upload-artifact@v4
      with:
        name: evaluation-reports
        path: eval/reports/
        retention-days: 30